# Top-level configuration
name = "coverwrite"
main = "index.ts"
compatibility_date = "2024-11-04"

[[unsafe.bindings]]
name= "RATE_LIMITER"
type = "ratelimit"
namespace_id = "904"
simple = { limit = 1, period = 60 }